
{{- if .Values.knativeDeploy }}
{{- else }}
{{- range $name, $val := .Values.brand }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $.Chart.Name }}-{{ $name }}"
  labels:
    draft: {{ default "draft-app" $.Values.draft }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
data: 
    config.yml: |-
        core:
          enabled: true
          address: "" 
          port: "8088"
          worker_num: 0
          queue_num: 0
          max_notification: 100
          sync: true
          feedback_hook_url: ""
          feedback_timeout: 10
          feedback_header:
            - x-gorush-token:4e989115e09680f44a645519fed6a976          
          mode: "release"
          ssl: false
          cert_path: "cert.pem"
          key_path: "key.pem"
          cert_base64: ""
          key_base64: ""
          http_proxy: ""
          pid:
            enabled: false
            path: "gorush.pid"
            override: true
          auto_tls:
            enabled: false 
            folder: ".cache"
            host: ""
        
        grpc:
          enabled: false
          port: 50051
        
        api:
          push_uri: "/send"
          stat_go_uri: "/stat/go"
          stat_app_uri: "/stat/app"
          config_uri: "/config"
          sys_stat_uri: "/sys/stats"
          metric_uri: "/metrics"
          health_uri: "/healthz"

        android:
          enabled: true
{{- if or (eq $name "qcplus") (eq $name "allianz") }}
          key_path: "{{ $val.android.key_path }}"
{{- else }}
          apikey: "{{ $val.android.api_key }}"
{{- end }}
          max_retry: 0 

        ios:
          enabled: true
{{- if $val.ios.key_file }}          
          key_path: "{{ $.Values.certs_dir }}{{ $val.ios.key_file }}"
          password: "{{ $val.ios.password }}"
          production: "{{ $val.ios.production }}"
          key_type: "{{ $val.ios.key_type }}"
{{- else }}
          key_base64: "{{ $val.ios.key_base64 }}"
          key_type: "{{ $val.ios.key_type }}"
          password: ""
          key_path: ""
          production: "{{ $val.ios.production }}"
          key_id: "{{ $val.ios.key_id }}"
          team_id: "{{ $val.ios.team_id }}"
{{- end }}        
          {{- if $val.ios.max_concurrent_pushes }}
          max_concurrent_pushes: {{ $val.ios.max_concurrent_pushes }}
          {{- else }}
          max_concurrent_pushes: 100
          {{- end }}
          max_retry: 0

        web:
          enabled: true
          {{- if $val.vapid }}
          vapid_public_key: {{ quote $val.vapid.publicKey }}
          vapid_private_key: {{ quote $val.vapid.privateKey }}     
          {{- else }}
          apikey: {{ quote $val.web.api_key }}
          {{- end }}
          max_retry: 0

        queue:
          engine: "local"
          nsq:
            addr: 127.0.0.1:4150
            topic: gorush
            channel: gorush
          nats:
            addr: 127.0.0.1:4222
            subj: gorush
            queue: gorush
          redis:
            addr: 127.0.0.1:6379
            group: gorush
            consumer: gorush
            stream_name: gorush

        log:
          format: "string"
          access_log: "stdout"
          {{- if $.Values.logLevel }}
          access_level: "{{ $.Values.logLevel }}"
          {{- else }}
          access_level: "debug"
          {{- end }}
          error_log: "stderr" 
          error_level: "error"
          hide_token: false
          hide_messages: false

        stat:
          engine: "memory"
          redis:
            cluster: false
            addr: "localhost:6379"
            password: ""
            db: 0
          boltdb:
            path: "bolt.db"
            bucket: "gorush"
          buntdb:
            path: "bunt.db"
          leveldb:
            path: "level.db"
          badgerdb:
            path: "badger.db"            
        Events:  <none>
{{- end }}        
{{- end }}
  