{{- if .Values.knativeDeploy }}
{{- else }}
{{- range $name, $val := .Values.brand }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $.Chart.Name }}-{{ $name }}"
  labels:
    draft: {{ default "draft-app" $.Values.draft }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
{{- if $.Values.deployAnnotations }}    
  annotations:      
{{ toYaml $.Values.deployAnnotations | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      draft: {{ default "draft-app" $.Values.draft }}
      app: {{ $.Chart.Name }}
      name: "{{ $.Chart.Name }}-{{ $name }}"
  replicas: {{ $.Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" $.Values.draft }}
        app: {{ $.Chart.Name }}
        name: "{{ $.Chart.Name }}-{{ $name }}"
{{- if $.Values.podAnnotations }}      
      annotations:   
{{ toYaml $.Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
    {{- with $.Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}    
      imagePullSecrets:
{{- range $tval := $.Values.jx.imagePullSecrets }}
      - name: {{ quote $tval }}
{{- end }}    
{{- if $.Values.serviceAccount.enabled }}
{{- if $.Values.serviceAccount.name }}
      serviceAccountName: {{ $.Values.serviceAccount.name }}
{{- else }}
      serviceAccountName: {{ $.Chart.Name }}
{{- end }}
{{- end }}    
      containers:
      - name: {{ $.Chart.Name }}
        {{- if not $val.tag }}
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"       
        {{- else }}
        image: "{{ $.Values.image.repository }}:{{ $val.tag }}"
        {{- end }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        env:
{{- range $pkey, $pval := $.Values.env }}
        - name: {{ $pkey }}
          value: {{ quote $pval }}
{{- end }}
        volumeMounts:
        - name: "{{ $.Chart.Name }}-{{ $name }}"
          mountPath: {{ $.Values.config_dir }}
{{- if $val.ios.key_file }}               
        - name: "{{ $.Values.certs.name }}-{{ $name }}-ios"
          mountPath: {{ $.Values.certs_dir }}
{{- end }}
{{- if $val.android.key_file }}               
        - name: "{{ $.Values.certs.name }}-{{ $name }}-android"
          mountPath: {{ $.Values.certs_dir }}
{{- end }}                 
        ports:
        - containerPort: {{ $.Values.service.internalPort }}
        readinessProbe:
          tcpSocket:
            port: {{ $.Values.service.internalPort }}
          initialDelaySeconds: {{ $.Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ $.Values.livenessProbe.periodSeconds }}
        livenessProbe:
          tcpSocket:
            port: {{ $.Values.service.internalPort }}
          initialDelaySeconds: {{ $.Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ $.Values.livenessProbe.periodSeconds }}
        resources:
{{ toYaml $.Values.resources | indent 12 }}
      {{- with $.Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      volumes:
      - name: "{{ $.Chart.Name }}-{{ $name }}"
        configMap:
          name: "{{ $.Chart.Name }}-{{ $name }}"
{{- if $val.ios.key_file }}          
      - name: "{{ $.Values.certs.name }}-{{ $name }}-ios"
        secret:
          secretName: {{ $.Values.certs.name }}-{{ $val.ios.key_file }}
{{- end }}
{{- if $val.android.key_file }}          
      - name: "{{ $.Values.certs.name }}-{{ $name }}-android"
        secret:
          secretName: {{ $.Values.certs.name }}-{{ $val.android.key_file }}
{{- end }}   
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}      
{{- end }}
{{- end }}
