apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: develop
spec:
  pipelineSpec:
    tasks:
    - name: build-gorush
      resources: {}
      retries: 1      
      taskSpec:
        metadata: {}
        stepTemplate:
          env: 
          - name: DEVELOP_VERSION
            value: 0.0.0-DEVELOP
          - name: ENVIRONMENT
            value: dkv-develop          
          image: uses:jaraxasoftware/jaraxa-pipeline-catalog/tasks/go/release.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jaraxasoftware/jaraxa-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
          script: |
            #!/usr/bin/env sh
            echo $DEVELOP_VERSION-$BUILD_ID > VERSION          
        - name: jx-variables
          resources:
            # override requests for the pod here
            requests:
              cpu: 400m
              memory: 600Mi
        - name: build-make-build
          resources: {}
          script: |
            #/bin/sh
            make build_linux_amd64          
        - name: check-registry
          resources: {}
        - name: build-container-build
          resources: {}
        - name: promote-changelog-uat
          resources: {}
        - name: promote-helm-release
          resources: {}
        - name: promote-jx-promote
          resources: {}  
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
