apiVersion: v2
name: gorush
description: Jaraxa implementation of Gorush on Kubernetes
home: https://github.com/jaraxasoftware/gorush/tree/staging/charts/gorush
version: 0.0.0-DEVELOP-1720513609975
appVersion: 0.0.0-DEVELOP-1720513609975
icon: https://jaraxa-public.s3.eu-central-1.amazonaws.com/LogoJRX-web.svg
maintainers:
- email: sergio.jurado@jaraxa.com
  name: Sergio Jurado
sources:
- https://github.com/jaraxasoftware/gorush
