# Default values for Go projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent

# optional list of image pull secrets to use to pull images
jx:
  # optional image pull secrets
  imagePullSecrets: []

  # whether to create a Release CRD when installing charts with Release CRDs included
  releaseCRD: true

# define environment variables here as a map of key: value
env:

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

deployAnnotations:
  wave.pusher.com/update-on-config-change: "true"

service:
  name: gorush
  type: ClusterIP
  externalPort: 8088
  internalPort: 8088
  annotations: []

resources: {}
  #limits:
  #  cpu: 100m
  #  memory: 256Mi
  #requests:
  #  cpu: 80m
  #  memory: 128Mi

probePath: /
config_dir: /config/
certs_dir: /certificates/
certs_dir_voip: /certificates_voip/
key: key_file

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

keda:
  enabled: false
  coolDown: 30
  interval: 30
  cron:
    start: 00 15 * * *
    end: 15 15 * * *
    timeZone: Europe/Madrid
  annotations: {}
  extraTriggers: {}

podSecurityContext: {}

securityContext: {}

certs:
  name: gorush-certs

brand:
  default:
    tag: 1.16.0
    ios:
      password: "changeme"
      key_file: "push.pem"
      max_concurrent_pushes: 100
    android:
      api_key: "AAAA4SKa3Qo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    vapid:
      publicKey: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
      privateKey: "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
  qcplus:
    ios:
      key_type: "p12"
      password: "changeme"
      key_file: "push.p12"
      production: false
      max_concurrent_pushes: 100
    android:
      key_file: "push-firebase-v2.json"
    vapid:
      publicKey: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
      privateKey: "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"

# custom ingress annotations on this service
ingress:
  annotations: {}
  # defaults to nginx if no other ingress class annotation specified
  classAnnotation: ""
  # Add labels to the ingress
  labels: {}

  # ingress path type
  pathType: ImplementationSpecific

serviceAccount:
  enabled: false
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  tokenAutomount: false  
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "" 

# values we use from the `jx-requirements.yml` file if we are using helmfile and helm 3
jxRequirements:
  ingress:
    # shared ingress annotations on all services
    annotations: {}
    #  kubernetes.io/ingress.class: nginx

    apiVersion: "networking.k8s.io/v1"

    # the domain for hosts
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    serviceType: ""
    tls:
      email: ""
      enabled: false
      production: false
      secretName: ""
